services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: urlShortDb
    volumes:
      - ./postgres:/var/lib/postgresql/data